class StepValueError(ValueError):
    """Исключение, выбрасываемое, когда шаг итерации равен 0."""
    pass


class Iterator:
    def __init__(self, start, stop, step=1):
        """Инициализация атрибутов итератора и проверка шага."""
        if step == 0:
            raise StepValueError('Шаг не может быть равен 0')

        self.start = start
        self.stop = stop
        self.step = step
        self.pointer = start

    def __iter__(self):
        """Сбрасывает указатель на начало итерации и возвращает объект итератора."""
        self.pointer = self.start
        return self

    def __next__(self):
        """Возвращает следующее значение в итерации или завершает итерацию."""
        if (self.step > 0 and self.pointer > self.stop) or (self.step < 0 and self.pointer < self.stop):
            raise StopIteration

        current = self.pointer
        self.pointer += self.step
        return current


# Пример использования
try:
    iter1 = Iterator(100, 200, 0)
    for i in iter1:
        print(i, end=' ')
except StepValueError:
    print('Шаг указан неверно')

iter2 = Iterator(-5, 1)
iter3 = Iterator(6, 15, 2)
iter4 = Iterator(5, 1, -1)
iter5 = Iterator(10, 1)

# Итерация по объекту iter2
for i in iter2:
    print(i, end=' ')
print()

# Итерация по объекту iter3
for i in iter3:
    print(i, end=' ')
print()

# Итерация по объекту iter4
for i in iter4:
    print(i, end=' ')
print()

# Итерация по объекту iter5
for i in iter5:
    print(i, end=' ')
print()
